### ISSUE TITLE
[Feature Request] Static optimization/analysis

### ISSUE THREAD

**Issue by altaic** [sharpie7/circuitjs1#122]
It seems like a bunch of the errors due to wire loops (and the resulting bug reports) could be avoided by a simple graph optimization behind the scenes before simulation (i.e., the simulated circuit would have a different representation than the displayed one). For example, each time the circuit is modified (or loaded), collapse wire loops into a single wire for the purposes of simulation, then divide the simulation result for each wire and display. Please forgive me if this suggestion is untenable or undesirable, as I am not very familiar with the simulator internals.

If it's not desired, a graph cycle analysis could be done each time the circuit is modified. If the circuit is malformed, it can then alert the user with a descriptive error (and guidance). In general, it would be nice to have better errors through static analysis, however, other than wire loops, I'm not sure what classes of errors could be captured this way.

**Comment by sharpie7** [comment]
Thanks for the thought. Actually the simulation already performs static analysis and simplification of circuits and uses this to detect wire loops.

The problem is that the simulation still has to display the state of all elements in the circuit using the topology as it is drawn by the user (including wire loops). For perfect wires (which the simulation uses) the current distribution over wire loops is undefined and therefore cannot be calculated.
