### ISSUE TITLE
Question: can a speaker be added to a circuit?

### ISSUE THREAD

**Issue by YakovL** [sharpie7/circuitjs1#141]
Hi, I'm not very educated in electronics, so it's not obvious for me: among the lists of stuff available to draw, is there a speaker or any analogue? (I don't see "speaker" itself, but may be I've overlooked some obvious synonym)

If there's no such thing, will this be much of a feature request? (probably most interesting implementation would be direct output to the user's speakers)

I'm trying to create a circuit for a radio (http://tinyurl.com/y9n84po2) but didn't get what can I use in it.

**Comment by sharpie7** [comment]
Actually, that turns out to be a really interesting question and it took me some time to make a radio that works. Here is my version of a classic "crystal set" circuit based on your example:
http://tinyurl.com/y9ra3uks

In fact, the "antenna" component is not a very good model of an antenna because its signals aren't actually at radio frequencies and also it doesn't have the right impedance. I've added resistors to the circuit to make it more like the real-world. With my example you can see tuning and demodulation of two AM signals from the antenna.

There is an "audio output" under Draw -> Outputs and Labels -> Add Audio Out which can substitute for a speaker, but because the frequencies in the antenna are lower than real-world RF and AF frequencies I don't think it would do anything useful in this model.
