### ISSUE TITLE
Can a speaker and a LM386 be added to the applet ?

### ISSUE THREAD

**Issue by smart-circuiter** [sharpie7/circuitjs1#145]
When I create a mini audio amp, I can't find a speaker symbol here. Only an analogue output is not enough cos I need to connect the speaker in series with the positive rail.

And also, LM386 is so common these days in the electronic world, why don't you add this component to your applet ?

**Comment by sharpie7** [comment]
You can use a resistor, or a resistor/inductor combination to simulate the electrical characteristics of a speaker. As long as one terminal of the speaker is connected to a DC level (like the positive rail) you can still connect audio out to the other terminal to hear the sound (because the DC offset has not effect on the sound) - like this:
http://tinyurl.com/yaewj7ve

This application is primarily about showing how electronics works using the essential building blocks. We don't really try and have precise models for specific components unless they have really had an enormous impact on the practice or teaching of electronics. On that basis we're not likely to add an LM386. You can find SPICE models of that component if you want to simulate it in a SPICE-based simulator.
