### ISSUE TITLE
[Feature Request] Can we have an optocoupler?

### ISSUE THREAD

**Issue by AC-Model** [sharpie7/circuitjs1#193]
For my developments it's very useful to have an optocoupler (something like Typ: CNY17-1-000E).
If it is possible, give me your support please.

Thank you

**Comment by bohix** [comment]
Same request please, or explain how to reproduce one with available components.
In my case models 6N137 and SFH620A.
Thank you!

**Comment by sharpie7** [comment]
It's a reasonable request to add an optocoupler to the project. Though, as I have said elsewhere, this project generally doesn't model particular components, but rather generic representations of components.

The problem is that I have never seen any general mathmatical model for the behaviour of an optocoupler. If someone knows one then please add a link to this discussion.

**Comment by ibelectronics** [comment]
It would be fine to add general optocoupler model (like PC817) to have galvanic isolation between input and output. Mr.Falstad, please add it into the circuit simulator. Thanks a lot.

**Comment by E3V3A** [comment]
I agree, optocouplers are surprisingly popular. I think they are even present in some Apple chargers.
