### ISSUE TITLE
If I choose the European Resistor and export the file, save as American Resistor

### ISSUE THREAD

**Issue by Lenioip** [sharpie7/circuitjs1#225]
Hi, please help me !
After I choose European Resistor, do my projects and go export the file like As Link (no problem) !
When I access the the link appears American Resistor instead European Resistor.
Thank so much for the help !
Best Regards
Lenio rodrigues

**Comment by pfalstad** [comment]
Hi,

the euro resistors setting isn't saved in the file or link.  Instead we try to guess the setting by looking at the browser language.  Or, if the user has selected one or the other, we use that setting. 
 Otherwise, someone who creates a circuit in the US could send it to someone in Europe and then the resistors would show up with the wrong symbols.

To force european resistors to be used, you can add euroResistors=true to the link like so:

http://www.falstad.com/circuit/circuitjs.html?euroResistors=true&cct=$+1+0.000005+10.20027730826997+50+5+43%0Ar+176+80+384+80+0+10%0As+384+80+448+80+0+1+false%0Aw+176+80+176+352+0%0Ac+384+352+176+352+0+0.000014999999999999999+-2.0928411374626705%0Al+384+80+384+352+0+1+0.009793135302664145%0Av+448+352+448+80+0+0+40+5+0+0+0.5%0Ar+384+352+448+352+0+100%0Ao+4+64+0+4099+10+0.05+0+2+4+3%0Ao+3+64+0+4099+10+0.05+1+2+3+3%0Ao+0+64+0+4099+0.625+0.05+2+2+0+3%0Ah+1+4+3%0A

If that's too long you can use a link shortener.

European resistors should be used by default everywhere except in the US or Canada.  If you're not seeing that then there might be a bug.
