### ISSUE TITLE
"m" is interpreted as "M" when change a resistance value

### ISSUE THREAD

**Issue by ghost** [sharpie7/circuitjs1#245]
When I'm setting the value of a resistor to, for example, 10m (milliohms), it's being set to 10M (megaohms).

**Comment by pfalstad** [comment]
I did that on purpose because I didn't think anyone would set a resistor to a value in milliohms.  Guess I was wrong.

**Comment by tungmetal** [comment]
I needed it only once, when I was simulating the ESR of a capacitor. It's not that hard to just type "0.025" instead of "25m", and millions of ohms occur much more often than the milliohms. However, I think all the conventions used inside one program should be consistent, so there wouldn't be any behavior that the user doesn't expect.

**Comment by sharpie7** [comment]
Fixed
