### ISSUE TITLE
Suggestion: "Advanced mode"

### ISSUE THREAD

**Issue by Felthry** [sharpie7/circuitjs1#276]
With the new diode code that was just added, I feel like this simulator is moving away from its previous role of being a very simple, easy-to-use circuit simulator. I feel like this simulator fills a niche that few others do: it's beginner-friendly, easy to pick up, and doesn't overload you with parameters to fill in. But at the same time, I think the expanded diode features are a good thing to have access to.

In order to remain beginner-friendly, yet also have the power of more advanced models with more configurable parameters, I had the idea that there could be a toggle for an "advanced mode" that exposes more functionality (such as the new diode options). Having this toggle turned off would hide away some of the more rarely used parameters to allow beginners to experiment with the basics, but turning it on would allow access to the full functionality of the engine.

I'm not sure just how difficult this would be to implement. If this is far beyond the realm of feasibility, then so be it, but I hope it would be something worth considering at least.

**Comment by pfalstad** [comment]
It seems like beginners can just use the default diode model...  or pick one of the predefined models.  You don’t even see the advanced diode parameters unless you jump through a bunch of hoops.

**Comment by sharpie7** [comment]
Yes, I am on the same page as Paul - I don't think the advanced options we've added reduce the accessibility to beginners - if you don't go looking for them they won't bite you. Overall I prefer to avoid the concept of different UI modes for beginners and experts. If you can design the UI sensibly you can structure things so advanced people can find them and beginners won't be bothered by them. 

Having said that, if there are specific areas where you think complexity has been added in an unfriendly way then we could look at whether there are options to address those.

**Comment by Felthry** [comment]
That's fair. Perhaps I'm having a hard time properly articulating my complaint about the new diode model; a large part of it is that if I want to use a specific forward voltage it takes quite a few steps to get to a point where I can. Perhaps that's wanting more complexity rather than less?

As for other unfriendly complexity--I've mentioned more than once my dissatisfaction with some of the parameters on some elements; _especially_ kg1 on triodes, which the only source for just says is "a parameter to fit the model to the data" with no elaboration. It's not easy to put in values from a datasheet when the datasheets don't list those values.

**Comment by sharpie7** [comment]
Thanks for that comment - that is a clearer guide as to the actual points of interest.

Generally I still think the primary purpose of the sim is as a learning tool and, as such, it is more oriented towards general classes of components rather than specific devices. I did see your comments about models and model parameters. I must admit the first time I saw the "kg1" description I laughed but it's not really much of a sim for pre-semiconductor devices. I know it's not the best answer, but all the code is available so you can reverse engineer that to see the models.

Unfortunately, data sheets are not intended to allow you to build simulation models of devices, so the best we can do is to take reasonable models for a component and offer some parameters to customize them to make them to represent real-world alternatives. But again I would think more about this in a fairly gross level - e.g. the difference between a power transistor and an RF transistor rather than offering complete configurability to match all the oddities of particular device.

**Comment by Felthry** [comment]
Alright. I can agree with that logic--but general classes rather than specific devices might be incompatible with the specific way the diode models are implemented.

My apologies if I've been flooding your inboxes with suggestions, by the way. I have ideas, and maybe not the best idea of how to articulate them. If I knew more about javascript I'd probably make at least some of those into pull requests instead, but I don't have the faintest idea how to do coding targeting anything more complex than a microcontroller.

**Comment by pfalstad** [comment]
If you can find another triode model that would be more appropriate, let me know.  I found this one: http://recherche.ircam.fr/pub/dafx11/Papers/76_e.pdf  but it has even more opaque parameters, not found on the datasheets, which are determined using curve fitting.  As Iain said, the datasheets are not intended to give you enough information to build a simulation model of a device.

**Comment by ormaaj** [comment]
Setting a zener voltage is mildly cumbersome with a new named diode needed for each. Though being able to edit one and have all of a kind adjusted accordingly is also useful. Would it be hard to have the old behavior with a quick access slider or edit field for the "default zener" together with the new functionality?

**Comment by pfalstad** [comment]
Diodes now have simple and advanced models.
