### ISSUE TITLE
Feature request: More computer components

### ISSUE THREAD

**Issue by SgtSchultz71** [sharpie7/circuitjs1#277]
I find the circuit simulator to have an excellent selection of digital components, but I would love to see more computer specific items. Some items I have in mind are things like Static Ram, EEPROMs, Digital Displays, more modular counters, etc. I have been successful in simulating simple computer machines but I think an expansion would be incredibly helpful.

**Comment by pfalstad** [comment]
I added static RAM and a modulus option to the counter.  The static RAM could act as a parallel EEPROM.  I think a serial EEPROM is too high-level for a simulator like this without a microcontroller.  Same for digital displays, although I did add an LED array.  Respond if you disagree (and you're still interested) and I might reconsider, otherwise I'll close this for now.

**Comment by SgtSchultz71** [comment]
Hey there! I did indeed notice the update and I think it's fantastic! Thank you for implementing it. I have been using software for cpu development now, but it's so convenient to have a browser-based simulator that offers components that can be used to demonstrate the concepts.
