### ISSUE TITLE
Reversed SPDT + inductor + spark plug behaviour

### ISSUE THREAD

**Issue by S119349** [sharpie7/circuitjs1#328]
Given the following circuit

```
$ 1 0.000005 10.20027730826997 50 5 50
S 208 176 256 176 0 0 false 0 2
w 256 192 336 192 0
w 336 160 336 192 0
g 336 192 336 224 0
l 144 176 208 176 0 1 0.000005005000000000001
R 144 176 112 176 0 0 40 5 0 0 0.5
187 256 160 336 160 0 1000 1000000000 1000 0.001
r 256 144 336 144 0 1000000
w 336 144 336 160 0
w 256 144 256 160 0
```

You can see that the current direction is reversed when flipping the switch, which is contrary to the expected behaviour.

**Comment by pfalstad** [comment]
Go to the inductor edit dialog and unchecked the box marked "Trapezoidal Approximation".  This should be unchecked on inductors that are switched.  It's checked by default because it's more accurate in AC and filter circuits, but if the inductor is switched, it creates instability, like you see here.
