### ISSUE TITLE
Bug - LEDs not turning on?

### ISSUE THREAD

**Issue by Ookgluk32** [sharpie7/circuitjs1#388]
[circuit-20190923-1718.circuitjs.txt](https://github.com/sharpie7/circuitjs1/files/3644539/circuit-20190923-1718.circuitjs.txt)
I am very new to this, in fact I just started today for school.
Basically, with the attached project, when the top number is 1 and the bottom number is 6, I want the green LED to turn on, when it's not 1 at the top and 6 at the bottom, I want the red LED to turn on. It looks to me as though current is flowing through the red LED... so why ism't it turning on?

**Comment by pfalstad** [comment]
The LED isn't connected to anything.  Attach the right terminal to ground.  Actually, attach the right terminal to a resistor and then to ground, or else you would fry the LED if this were a real circuit.

Also you should change the LED max brightness current back to 10m, because having it at 0 is not realistic.
