### ISSUE TITLE
The problem with the example amplifier

### ISSUE THREAD

**Issue by stasserov** [sharpie7/circuitjs1#391]
After overloading the circuit, the signal of the amplifier with a common emitter is shifted above zero.

Demo video: https://drive.google.com/file/d/1hP4ez43Am4QnvqTvNLuzqlKgp8mkyl5u/view?usp=sharing

**Comment by tetoskare** [comment]
Hi, in your example you don't seem to have "overloaded" the amplifier with a strong signal on the input, you just hit the "Reset" button. It will take some time to the capacitor on the right to filter DC at the moment of turning-on the circuit, this is normal. It's the PLOP you hear on your speakers when turning on an amplifier (if it doesn't has an internal delay switch for the speakers). In this circuit, the RC constant will have an effect on how much time it will take to settle around 0V. Because the load (1M resistor) is enormous, and the filter (5µ capacitor) is quite large, it takes about 20 seconds. 
The trick is that the example-circuit doesn't start at a real 0s time when it loads from the library, though it does when you click the Reset button.
Try playing with the load and capacitor values to see this filtering time go quicker, Or use a larger "time step size" (in Option / Other Option) to see the waveform go back to normal cycling around 0V after a little while.
