### ISSUE TITLE
User Manual

### ISSUE THREAD

**Issue by SM-Fahim** [sharpie7/circuitjs1#394]
I badly need a user manual as a new user of this software. I'm trying to solve the problem in the attachment But don't understand how to plot the graph. One of the images shows the problem, another shows the graph.

I don't find any other place to find the solution, so asking it here as an issue. 

![issue1](https://user-images.githubusercontent.com/30735259/69015804-1cd13700-09c2-11ea-8b3d-a79581382f83.png)
![issue1 1](https://user-images.githubusercontent.com/30735259/69015803-1cd13700-09c2-11ea-9502-56a44518b3c1.png)

**Comment by pfalstad** [comment]
To view I1 vs V1 you can just right click on the voltage source and select View in Scope, right click on the scope and select Properties, then View V vs I.  It won't be much help here though because it doesn't show a scale.

To view I2 vs V1 you would need to plot I2 and V1 seperately, then combine them (right click on the second one and select Combine), then Properties->plot XY.  Again, there's no scale shown and you can't match it to the first graph so it won't be much help.

**Comment by SM-Fahim** [comment]
Okay sir, I solved my problem separately. i'll be deleting this issue, but before that, could you tell me how can I use an AC current source? I need it to represent 5cos2t A. Couldn't find it.

**Comment by pfalstad** [comment]
here you go: http://tinyurl.com/vsf79ee

create voltage-controlled current source, set function to 5*cos(2*t), no inputs.

**Comment by SM-Fahim** [comment]
Actually I'm trying to solve this circuit from last night, without any rest, and didn't see any improvement. Can you help me? And I can't set the value for that current source. It would be very helpful for me if you help me.
![mail](https://user-images.githubusercontent.com/30735259/69023803-54ec7000-09ea-11ea-9f06-8a01a3d9746d.png)

**Comment by sharpie7** [comment]
There are tutorial videos for basic operations in my page: http://lushprojects.com/circuitjs/
