### ISSUE TITLE
Calculating methods

### ISSUE THREAD

**Issue by popkingcorn** [sharpie7/circuitjs1#447]
Hi,
What method/algorithm do you use to calculate the circuits?
Maybe you can recommend some literature to find out.

**Comment by pfalstad** [comment]
This is the book I used, it's very good: https://www.amazon.com/Electronic-Circuit-System-Simulation-Methods/dp/0070501696

**Comment by colinhowell** [comment]
There's also the original papers on SPICE:

https://www2.eecs.berkeley.edu/Pubs/TechRpts/1975/9602.html
https://www2.eecs.berkeley.edu/Pubs/TechRpts/1973/22871.html

They're old, but they provide a useful explanation of how this stuff is done. The first-listed paper is later (1975) but is much longer and goes into far more detail; I also included the second-listed paper (from 1973) because it adds more background on SPICE's development.

SPICE is an ancient program, but the methods still work--and compared to the original low-end supercomputers they first ran on, modern hardware is fast enough to run them on the fly in interactive Javascript!

**Comment by popkingcorn** [comment]
So circuit calculated by solving set of nodal equations based on KCL (lu_solve function in code), did I understand correctly?

**Comment by pfalstad** [comment]
That’s right.

**Comment by popkingcorn** [comment]
Thanks for answers!
