### ISSUE TITLE
economy switch schematic leads to error

### ISSUE THREAD

**Issue by jkischel** [sharpie7/circuitjs1#466]
If you're building up an economy switch schematic like descibed under 
https://dein-elektriker-info.de/wp-content/uploads/2018/03/Sparwechselschaltung.png

it leads to errorous output (current comes out ouf nowhere), if you change the switches, simulation stops
![circuitjs_sparwechselschaltung](https://user-images.githubusercontent.com/11940089/87246244-69371e80-c44c-11ea-929c-a27f58f5087e.png)

**Comment by pfalstad** [comment]
I can't reproduce this, could you send me the circuit?  Go to File->Export as Link...

**Comment by Felthry** [comment]
Attempting to draw this circuit gives a matrix error due to the wire loop with no resistance created by the switches in this configuration. If you then click run/stop anyway, this reproduces the bug.

![an image of the same bug as above, but with the text "matrix error" visible in the lower left.](https://user-images.githubusercontent.com/6402030/88391458-d36e8e00-cd7f-11ea-9355-b43b680af077.png)

Flipping either switch restores the simulation to normal working order, and flipping them again gives another matrix error, stopping the simulation as the initial bug report said.

**Comment by pfalstad** [comment]
Yes, that's probably it.

**Comment by sharpie7** [comment]
Fixed
