### ISSUE TITLE
Diode behavior seems to be incorrect

### ISSUE THREAD

**Issue by atomroflman** [sharpie7/circuitjs1#563]
I've been creating a circuit to check if a 12V input is switched or not.

My expectation is, that the diode blocks voltage from the 12V line and the 3.3V should be measured at the output if 12V is connected. If the switch is open the measurement should be close to the diode voltage loss.

![image](https://user-images.githubusercontent.com/10799353/108984067-cefcb180-768f-11eb-9b92-5c54b7b6c04b.png)

Correct me if I am wrong, but I think the calculation seems to be wrong.

**Comment by pfalstad** [comment]
Well, the position of the switch doesn't matter at all, since the left side of the 1k resistor is going to be at 0V no matter what.  The switch position only affects the current through the 100 ohm resistor.

Because the 1 megaohm resistor is there, the current through the diode is going to be very small and a voltage drop of about 150 mV sounds about right.  The diode voltage drop depends on current of course.
