### ISSUE TITLE
plot: AC source average power missing

### ISSUE THREAD

**Issue by jfcg** [sharpie7/circuitjs1#567]
In the [simulator](https://www.falstad.com/circuit/circuitjs.html):
- Choose Circuits > Diodes > Voltage Multipliers > Voltage Doubler
- In settings of resistor plot at the bottom right, check `Auto (max scale), Show power consumed, Show average` and uncheck `Show peak value`
- In settings of AC source plot at the bottom left, check `Show power consumed, Show average` and uncheck `Show peak value`
- Observe about -84 and 79.5 mW on the plots
- Change AC source frequency from 40 to 80 Hz
- Average power calculation on the AC source plot vanishes, but resistor average power seems fine
- Change AC source frequency back to 40 Hz, AC source average power calculation comes back

**Comment by pfalstad** [comment]
It comes back if you speed up the plot (change the horizontal scale to 5 ms/div or turn the mouse wheel down slightly).  The problem is that the simulator is trying to average over one cycle and it's apparently having trouble identifying the cycles when the speed is too slow.  If you speed it up, the data has higher resolution so it's easier to figure out what's going on.
