### ISSUE TITLE
Request for relay symbol update according to IEC-60617

### ISSUE THREAD

**Issue by tito125** [sharpie7/circuitjs1#618]
Hello,

I have made a circuit with relays and time relays, only it becomes unreadable with this type of symbol.
Would it be possible to modify the relay and timer symbols to the international standard IEC-60617.

Relay with NO and NC contact

<a href="https://zupimages.net/viewer.php?id=21/23/t9yt.jpg"><img src="https://zupimages.net/up/21/23/t9yt.jpg" alt="" /></a>

Symbol link :

https://help.autodesk.com/view/ACAD_E/2019/FRA/?guid=GUID-DA927086-EEAF-48CB-B9B1-634A4B48C8C7

And 

https://help.autodesk.com/view/ACAD_E/2019/FRA/?guid=GUID-2729322A-CC84-4ADD-AF7C-A651DCA7CE02

Many thanks in advance

**Comment by nulldg** [comment]
Unless I'm not being very imaginative, the relevant symbols prescribed by IEC-60617 doesn't appear to be very good for illustrating the internal state of the relay, which is important for the circuit simulation.
We can mitigate the ambiguity by adding some kind of rectangle around the relay. What do you think?
![image](https://user-images.githubusercontent.com/55410457/121724106-4e977a80-cadf-11eb-96af-bedc1853f0c8.png)

**Comment by pfalstad** [comment]
The IEC symbols are all two- or three-terminal devices, also.  As far as I can tell, the time delay relay symbols don't show the power connections, and the relay symbols don't show the coil.

**Comment by tito125** [comment]
Hello,
Yes, indeed, it looks like that for simple relays, I modified the image and put an example of a typical relay that would correspond more to the standard.

Cordially
![ohdakekmcfnllgpk](https://user-images.githubusercontent.com/53943846/123611838-4be89500-d802-11eb-8b57-c449dd3d01d3.jpg)

**Comment by nulldg** [comment]
We've already created and added the change (https://github.com/pfalstad/circuitjs1/pull/13). It's now on paul's public build of circuitjs if you'd like to play with it.
We could probably further improve it by:
- changing the outline to be a dotted rather than a solid.
- an option to move one of the relay coil's terminals to the opposite end of the relay rather than looping back

But this might be getting rather excessive. I think the way it looks now is quite nice.
![image](https://user-images.githubusercontent.com/55410457/123615913-a6332700-d7fd-11eb-85e7-3e235101d5c5.png)
![image](https://user-images.githubusercontent.com/55410457/123616503-438e5b00-d7fe-11eb-94fa-9c35fe756d9b.png)

**Comment by pfalstad** [comment]
Well we should try to look like the standard symbol as much as possible.  The relays need work anyway so these would be good changes to make.

**Comment by nulldg** [comment]
I think we should replace the "Swap Coil Direction" checkbox with a listbox for the different coil styles: default, flipped, and straight. We might need to replace the `FLAG_SWAP_COIL` flag with a style integer to accept more than 2 styles. Or maybe not. I'm not entirely sure how to write this cleanly without changing the `FLAG_SHOW_BOX`'s value we added very recently

**Comment by pfalstad** [comment]
yes we should have a listbox (though I would make straight the default).  Internally though, I'd just keep FLAG_SWAP_COIL and add another flag for straight.

**Comment by nulldg** [comment]
What happens if both flags are high? What if we want to add more styles?

**Comment by pfalstad** [comment]
well the UI code will make sure only valid combinations of flags are allowed.

there's plenty of room for more flags.  how many coil styles can there be?  we're already stuck with FLAG_SWAP_COIL so sticking with flags seems the simplest.

**Comment by nulldg** [comment]
Fair enough, I agree. I'm just thinking ahead, because I doubt this was anticipated when the "swap coil direction" option was added. Once we make a change to the dump format, we can't undo it without adding legacy code, but if we ever do need to add another in the future, we could just treat the flags as the bits of a 2-bit integer.

**Comment by K0rrid0r** [comment]
This was a great update, thanks!
