### ISSUE TITLE
Features:export to electronic schematic image files

### ISSUE THREAD

**Issue by annopnod** [sharpie7/circuitjs1#74]
convert circuit to image file

**Comment by E3V3A** [comment]
This would be not only cool, but very useful!
Then we no longer need to make screen shots from other apps. 

The only issue I see with this, is the large horizontal size (due to most wide screen settings). 
It would such to keep looking at 1080+ wide circuits, where most of it is empty black space on the sides. 
So some additional logic would be needed to minimize the images.
