### ISSUE TITLE
Low pass filter (RC) has cutoff frequency error

### ISSUE THREAD

**Issue by dxhowardjack** [sharpie7/circuitjs1#793]
Hi,

I'm trying the cutoff frequency formula f=1/(2*pi * r * c) on the Low pass filter example circuit.
And I found it seems have 10 times error on frequency parameter. (divide the frequency by 10 would be true value)

I'm new to Electronic Engineering, feel sorry if I am wrong.
Thank you.

**Comment by pfalstad** [comment]
hi,

f = 1/(2*pi*r*c) = 85.11 Hz

If I replace the sweep input with a AC source fixed at 85.11 Hz:

https://tinyurl.com/2o8duapx

I get a peak output of 3.536 V, which is .7072 * the peak voltage of the source.  power is proportional to the square of the voltage so that's .7072^2 = 1/2 the peak power of the source, as expected.
