### ISSUE TITLE
RMS value is dependent on time division

### ISSUE THREAD

**Issue by by-justin** [sharpie7/circuitjs1#968]
The Vrms value changes when I zoom in/out of the scope or change the horizontal scale in scope properties. This sine voltage source displays 2.977 Vrms when time division is set to 1ms/div and 3.386Vrms when set to 500us/div.

<img width="626" alt="image" src="https://github.com/user-attachments/assets/3303a6b4-b377-43dc-b1e9-c7e4cc266f95">

Moreover, Vrms value will not display on high frequency circuits. Adjusting timestamp size changes rms value as well.

[circuit-20241103-0940.circuitjs.txt](https://github.com/user-attachments/files/17611234/circuit-20241103-0940.circuitjs.txt)

**Comment by pfalstad** [comment]
Yes, that's true.  This isn't really fixable.  We calculate Vrms from the data we have available.  If the scope is zoomed in, there's more data for each cycle so the value will be more accurate.  Also if the timestamp size is smaller, the value will be more accurate for the same reason.

If the scope is zoomed in too far, we don't show a Vrms value at all because we don't have enough good data.

**Comment by by-justin** [comment]
Thanks for the clarification!
